# Generated by Django 2.2 on 2019-04-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrite',
            name='description',
            field=models.TextField(null=True, verbose_name='作品描述'),
        ),
    ]
