# Generated by Django 2.1.7 on 2019-03-21 13:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190321_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Union')),
            ],
        ),
    ]
