# Generated by Django 2.1.7 on 2019-03-20 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190318_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=0, verbose_name='用户状态'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
