# Generated by Django 2.2 on 2019-04-12 02:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_handwrite_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='评论内容')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('handwrite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.HandWrite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
