# Generated by Django 2.1.7 on 2019-03-23 06:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_unioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrite',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='handwrite',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.User'),
            preserve_default=False,
        ),
    ]
