# Generated by Django 2.1.7 on 2019-04-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='union',
            name='file_path',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
