# Generated by Django 2.1.7 on 2019-03-23 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190323_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='union',
            name='users',
            field=models.ManyToManyField(related_name='members', to='user.User'),
        ),
        migrations.AlterField(
            model_name='union',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='user.User', verbose_name='管理者'),
        ),
    ]
