# Generated by Django 2.1.7 on 2019-03-24 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190323_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrite',
            name='category_super',
            field=models.IntegerField(default=0, null=True, verbose_name='管理员的分类'),
        ),
        migrations.AlterField(
            model_name='handwrite',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
