# Generated by Django 2.1.7 on 2019-03-31 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190324_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='handwrite',
            name='in_union',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Union'),
        ),
    ]
